esphome:
  name: ${devicename}
  friendly_name: "${friendly_devicename}"
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  domain: .lan

  ap:
    ssid: "${friendly_devicename} fallback"
    password: !secret wifi_password

#logger:
#  baud_rate: 0 # (UART logging interferes with cse7766)  

ota:

web_server:
  port: 80
  local: true
  include_internal: true

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: status
    name: "${friendly_devicename}: Status"

sensor:
  - platform: wifi_signal
    name: "${friendly_devicename}: WiFi Signal"
    id: "${devicename_no_dashes}_signal"
    update_interval: 60s
    
  - platform: cse7766
    update_interval: 3s
    
    current:
      name: "${friendly_devicename}: Current"
      id: "${devicename_no_dashes}_current"
      state_class: measurement
      device_class: current
      unit_of_measurement: A
      accuracy_decimals: 2
      filters:
        - or:
          - throttle: 60s
          - delta: 0.5
          
    voltage:
      name: "${friendly_devicename}: Voltage"
      id: "${devicename_no_dashes}_voltage"
      state_class: measurement
      device_class: voltage
      unit_of_measurement: V
      accuracy_decimals: 2
      filters:
        - or:
          - throttle: 60s
          - delta: 0.5
          
    power:
      name: "${friendly_devicename}: Power"
      id: "${devicename_no_dashes}_power"
      state_class: measurement
      device_class: power
      unit_of_measurement: W
      accuracy_decimals: 2
      filters:
        - or:
          - throttle: 60s
          - delta: 50
          
  - platform: total_daily_energy
    name: "${friendly_devicename}: Daily Energy"
    power_id: "${devicename_no_dashes}_power"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kW
    state_class: total_increasing
    device_class: energy
    # 3 shows each W consumed, 2 every 10W, 1 every 100W
    accuracy_decimals: 2

text_sensor:
  - platform: wifi_info
  
    ip_address:
      name: "${friendly_devicename}: IP"
      icon: "mdi:ip-outline"
      
    ssid:
      name: "${friendly_devicename}: SSID"
      icon: "mdi:wifi-settings"
      
    bssid:
      name: "${friendly_devicename}: BSSID"
      icon: "mdi:wifi-settings"
      
    mac_address:
      name: "${friendly_devicename}: MAC"
      icon: "mdi:network-outline"
      
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

switch:
  - platform: gpio
    name: "${friendly_devicename}"
    icon: "mdi:power-socket-us"
    pin: GPIO12
    id: relay
    internal: true
    restore_mode: ALWAYS_ON

time:
  - platform: sntp
    id: home
    timezone: EST5EDT,M3.2.0,M11.1.0
    update_interval: 15min
    servers:
      - 10.0.0.1

status_led:
  pin:
    number: GPIO13
    inverted: True
