esphome:
  name: ${devicename}

esp8266:
  board: esp01_1m
  restore_from_flash: true
  
preferences:
  flash_write_interval: 15min

#api:
#  reboot_timeout: 0s

#logger:
#  baud_rate: 0 # (UART logging interferes with cse7766)
#  logs:
#    sensor: INFO
    
uart:
  rx_pin: RX
  baud_rate: 4800

switch:
  - platform: gpio
    name: "${devicename}"
    pin: GPIO12
    id: relay
    internal: true
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: True

<<: !include .ota.yaml
<<: !include .sensor.yaml
<<: !include .text_sensor.yaml
<<: !include .time.yaml
<<: !include .web_server.yaml
<<: !include .wifi.yaml
<<: !include .s31-binary_sensor.yaml